# 参考:
# https://hub.docker.com/_/mongo
# https://qiita.com/r1wtn/items/c18e14375bbaa564e289

services:

  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: photo-share-api-db
    ports:
      - 27017:27017
    volumes:
      - ./volume_data/mongo/db:/data/db
      - ./volume_data/mongo/configdb:/data/configdb
      - ./data/mongo/init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:1.0.2
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
